baseurl                 = "https://aestears.github.io/"
languageCode  = "en"
title                   = "Alice Stears"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "linkedin", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "Alice Stears professional research website"
    author              = "Alice Stears"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Alice Stears Research"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Alice Stears, PhD"
    paragraph             = "Postdoctoral Research Associate, University of Wyoming & NSF EPSCoR Modelscape Consortium </p> <p> Plant Population and Community Ecology & Data Science  </p> <p> <b> <a href='http://www.astearsresearch.com/about/images/AStears_CV_2023_1.pdf'>Curriculum Vitae</a> </b> </p>"
    rssIntro              = false
    socialIntro           = true
    hideWhenSingleColumn  = true
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/JujuAlicePhoto.jpg"
      shape               = "circle"
      width               = "200"
      alt                 = "Alice Stears Bio Photo"

  [params.sidebar]
    about               = "Alice Stears's professional research website."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = false
    socialFooter        = true

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='fas fa-smile'></i>"
    weight            = 2


  [[menu.main]]
    name              = "Research"
    identifier        = "research"
    url               = "/research/"
    pre               = "<i class='fas fa-leaf'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='fas fa-tree'></i>"
    weight            = 4

[[menu.main]]
    name              = "plantTracker"
    identifier        = "plantTracker"
    url               = "/package/"
    pre               = "<i class='fas fa-star'></i>"
    weight            = 5
    
 [[menu.main]]
    name              = "Fun"
    identifier        = "fun"
    url               = "/fun/"
    pre               = "<i class='fas fa-bicycle'></i>"
    weight            = 6
    

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1


[social]
  # Coding Communities
  github                = "aestears"
  #gitlab                = ""
  #stackoverflow         = "" # User Number
  #bitbucket             = ""
  #jsfiddle              = ""
  #codepen               = ""
  # Visual Art Communities
  #deviantart            = ""
  #flickr                = "example"
  #behance               = ""
  #dribbble              = ""
  # Publishing Communities
  #wordpress             = ""
  #medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "alice-stears-153415b9"
  #linkedin_company      = "examplebusiness"
  #foursquare            = ""
  #xing                  = ""
  #slideshare            = ""
  # Social Networks
  #facebook              = "example"
  #googleplus            = ""
  #reddit                = "example"
  #quora                 = ""
  #youtube               = ""
  #vimeo                 = ""
  #whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    #wechat              = ""
    #qq                  = "" # User ID Number
  #instagram             = "example"
  #tumblr                = ""
  twitter               = "alice_stears"
  #strava                = ""
  #skype                 = ""
  #snapchat              = ""
  #pinterest             = "example"
  #telegram              = "example"
  #vine                  = ""
  #googlescholar         = ""
  orcid                 = "0000-0002-1325-6641"
  researchgate          = "Alice-Stears"
  #keybase               = "example"
  #mastodon              = "example.com/@example"
  # Email
  email                 = "astears@uwyo.edu"
